/*********************信用等级评估模型  --- 代码管理 -- 信用评级***************分隔线*********************************/


-- sdong 	20151125 	有些要求的代码值数据库没有，需要增加 一些取值代码 到code_catalog ，	在 信用评估练习  中使用这些代码取值。
/*
select * from code_catalog where codeno in (
'd企业产权制度',
'd产销率',
'd国家产业政策',
'd地方产业政策',
'd行业门槛',
'd法律保障',
'd职称',
'd工作证或客户经理调查',
'd工作证或相关岗位证明',
'd工作年限',
'd收入证明调查',
'd家庭资产负债比率',
'd家庭资产总额',
'd信用记录',
'd与我行往来情况',
'd纳税情况',
'd投保情况',
'd有无');
*/

INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d与我行往来情况','00203919','2.信用评级','个人信用等级评估','与我行往来情况','','','SYS_Designer',null,'2015/11/25 14:43:39','SYS_Designer','2015/11/25 14:43:39','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d产销率','00200248','2.信用评级','企业信用等级评估','产销率','','','SYS_Designer',null,'2015/11/26 09:15:09','SYS_Designer','2015/11/26 09:15:09','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d企业产权制度','00200247','2.信用评级','企业信用等级评估','企业产权制度','','','SYS_Designer',null,'2015/11/25 19:14:50','SYS_Designer','2015/11/25 19:14:50','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d信用记录','00203487','2.信用评级','个人信用等级评估','信用记录','','','SYS_Designer',null,'2015/11/25 14:38:15','SYS_Designer','2015/11/25 14:38:15','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d国家产业政策','00200249','2.信用评级','企业信用等级评估','当地产业政策','','','SYS_Designer',null,'2015/11/26 09:51:56','SYS_Designer','2015/11/26 09:53:00','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d地方产业政策','00200250','2.信用评级','企业信用等级评估','地方产业政策','','','SYS_Designer',null,'2015/11/26 09:53:20','SYS_Designer','2015/11/26 09:53:20','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d家庭资产总额','00203055','2.信用评级','个人信用等级评估','家庭资产总额','','','SYS_Designer',null,'2015/11/25 14:31:56','SYS_Designer','2015/11/25 14:31:56','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d家庭资产负债比率','00202623','2.信用评级','个人信用等级评估','家庭资产负债比率','','','SYS_Designer',null,'2015/11/25 14:29:50','SYS_Designer','2015/11/25 14:29:50','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d工作年限','00201759','2.信用评级','个人信用等级评估','工作年限','','','SYS_Designer',null,'2015/11/25 14:21:02','SYS_Designer','2015/11/25 14:21:08','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d工作证或客户经理调查','00200895','2.信用评级','个人信用等级评估','工作证或客户经理调查','','','SYS_Designer',null,'2015/11/25 14:07:20','SYS_Designer','2015/11/25 14:07:20','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d工作证或相关岗位证明','00201327','2.信用评级','个人信用等级评估','工作证或相关岗位证明','','','SYS_Designer',null,'2015/11/25 14:15:49','SYS_Designer','2015/11/25 14:18:12','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d投保情况','00204783','2.信用评级','个人信用等级评估','投保情况','','','SYS_Designer',null,'2015/11/25 14:54:21','SYS_Designer','2015/11/25 14:54:21','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d收入证明调查','00202191','2.信用评级','个人信用等级评估','收入证明调查','','','SYS_Designer',null,'2015/11/25 14:25:40','SYS_Designer','2015/11/25 14:25:40','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d有无','00205215','2.信用评级','个人信用等级评估','有无与个人信用有关的民事纠纷','','','SYS_Designer',null,'2015/11/25 14:56:15','SYS_Designer','2015/11/25 14:56:32','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d法律保障','00200252','2.信用评级','企业信用等级评估','法律保障','','','SYS_Designer',null,'2015/11/26 10:01:07','SYS_Designer','2015/11/26 10:01:07','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d纳税情况','00204351','2.信用评级','个人信用等级评估','纳税情况','','','SYS_Designer',null,'2015/11/25 14:52:39','SYS_Designer','2015/11/25 14:52:39','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d职称','00200463','2.信用评级','个人信用等级评估','职称','','','SYS_Designer',null,'2015/11/25 13:39:57','SYS_Designer','2015/11/25 13:41:07','');
INSERT INTO code_catalog (CODENO,SORTNO,CODETYPEONE,CODETYPETWO,CODENAME,CODEDESCRIBE,CODEATTRIBUTE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('d行业门槛','00200251','2.信用评级','企业信用等级评估','行业门槛','','','SYS_Designer',null,'2015/11/26 09:57:41','SYS_Designer','2015/11/26 09:57:41','');



-- sdong 	20151125 	增加 客户个人信用评估练习’  到 Evaluate_catalog ，	表示 在个人信用等级评估中增加 客户个人信用评估练习  评估模型
--	select * from Evaluate_catalog where modelno = 'ds101'

INSERT INTO Evaluate_catalog  VALUES ('ds101','客户个人信用评估练习','015','','if(#TotalScore<40,"D",if(#TotalScore<45,"C",if(#TotalScore<49,"CC",if(#TotalScore<59,"CCC",if(#TotalScore<65,"B",if(#TotalScore<69,"BB",if(#TotalScore<79,"BBB",if(#TotalScore<85,"A",if(#TotalScore<89,"AA","AAA")))))))))','');





-- sdong 	20151125 	在客户个人信用评估练习中增加相应字段
--	select * from evaluate_model  where modelno = 'ds101'

INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','01','1','个 人 基 本 情 况','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','02','1.1','年龄','','','贷款申请人年龄','Number','if(#ItemValue=1,1,if(#ItemValue=2,2,if(#ItemValue=3,3,if(#ItemValue=4,4,if(#ItemValue=5,5,0)))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','03','1.2','户口','','','户口','Number','if(#ItemValue=1,3,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','04','1.3','在本地居住时间','','','在本市居住时间','Number','if(#ItemValue=1,0,if(#ItemValue=2,1,if(#ItemValue=3,2,if(#ItemValue=4,3,0))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','05','1.4','学历','','','职称或最高学历','Number','if(#ItemValue=1,4,if(#ItemValue=2,3,if(#ItemValue=3,2,if(#ItemValue=4,1,0))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','06','1.5','职称','','','d职称','Number','if(#ItemValue=1,3,if(#ItemValue=2,2,if(#ItemValue=3,1,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','07','1.6','婚姻状况','','','婚姻状况','Number','if(#ItemValue=1,3,if(#ItemValue=2,2,if(#ItemValue=3,1,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','08','1.7','居住状况','','','房产状况','Number','if(#ItemValue=1,3,if(#ItemValue=2,2,if(#ItemValue=3,1,-3)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','09','2','个人就业情况','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','10','2.1','行业或企业类别','','','d工作证或客户经理调查','Number','if(#ItemValue=1,9,if(#ItemValue=2,8,if(#ItemValue=3,7,if(#ItemValue=4,6,if(#ItemValue=5,5,if(#ItemValue=6,4,if(#ItemValue=7,3,if(#ItemValue=8,2,if(#ItemValue=9,1,0)))))))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','11','2.2','从事岗位','','','d工作证或相关岗位证明','Number','if(#ItemValue=1,7,if(#ItemValue=2,6,if(#ItemValue=3,5,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','12','2.3',' 从事目前行业年限或目前单位工作年限','','','d工作年限','Number','if(#ItemValue=1,1,if(#ItemValue=2,2,if(#ItemValue=3,3,if(#ItemValue=4,4,if(#ItemValue=5,5,if(#ItemValue=6,6,0))))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','13','3','个人资产情况','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','14','3.1','个人平均月收入','','','d收入证明调查','Number','if(#ItemValue=1,12,if(#ItemValue=2,10,if(#ItemValue=3,8,if(#ItemValue=4,6,if(#ItemValue=5,4,if(#ItemValue=6,2,0))))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','15','3.2','家庭资产负债比率','','','d家庭资产负债比率','Number','if(#ItemValue=1,6,if(#ItemValue=2,3,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','16','3.3','家庭资产总额','','','d家庭资产总额','Number','if(#ItemValue=1,16,if(#ItemValue=2,14,if(#ItemValue=3,12,if(#ItemValue=4,10,if(#ItemValue=5,8,if(#ItemValue=6,6,if(#ItemValue=7,4,0)))))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','17','4','个人信用','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','18','4.1','信用记录','','','d信用记录','Number','if(#ItemValue=1,10,if(#ItemValue=2,9,if(#ItemValue=3,8,if(#ItemValue=4,7,if(#ItemValue=5,6,if(#ItemValue=6,5,if(#ItemValue=7,4,if(#ItemValue=8,0,if(#ItemValue=9,-6,if(#ItemValue=10,-8,if(#ItemValue=11,-10,0)))))))))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','19','4.2','与我行往来情况','','','d与我行往来情况','Number','if(#ItemValue=1,5,if(#ItemValue=2,4,if(#ItemValue=3,3,if(#ItemValue=4,2,if(#ItemValue=5,1,0)))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','20','5','社会公共信息记录','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','21','5.1','纳税情况','','','d纳税情况','Number','if(#ItemValue=2,1,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','22','5.2','投保情况','','','d投保情况','Number','if(#ItemValue=2,1,if(#ItemValue=4,1,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','23','5.3','有无与个人信用有关的民事纠纷','','','d有无','Number','if(#ItemValue=2,1,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds101','24','5.4','有无与个人信用有关的行政处罚记录','','','d有无','Number','if(#ItemValue=2,1,0)',1.000000,'');


/*********************信用等级评估模型  --- 企业信用等级评估***************分隔线*********************************/

-- sdong 	20151125 	增加 企业信用评估练习’  到 Evaluate_catalog ，	表示 在企业信用等级评估中增加 企业信用评估练习 评估模型
--	select * from Evaluate_catalog where modelno = 'ds100'

INSERT INTO Evaluate_catalog (MODELNO,MODELNAME,MODELTYPE,MODELDESCRIBE,TRANSFORMMETHOD,REMARK) VALUES ('ds100','企业信用评估练习','010','','if(#TotalScore<40,"D",if(#TotalScore<45,"C",if(#TotalScore<49,"CC",if(#TotalScore<59,"CCC",if(#TotalScore<65,"B",if(#TotalScore<69,"BB",if(#TotalScore<79,"BBB",if(#TotalScore<85,"A",if(#TotalScore<89,"AA","AAA")))))))))','');



-- sdong 	20151125 	在企业客户概况中的  信用等级评估模板名称  选择列表中加入  刚刚添加的模板    企业信用评估练习(编号ds100)
															--  这样在选择列表中就可以选择该模板
--	select * from code_library  where codeno = 'CreditTempletType' and itemno='ds100'

INSERT INTO code_library (CODENO,ITEMNO,ITEMNAME,BANKNO,SORTNO,ISINUSE,ITEMDESCRIBE,ITEMATTRIBUTE,RELATIVECODE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK,HELPTEXT) VALUES ('CreditTempletType','ds100','企业信用评估练习','','ds100','1','ds100','','','','','','','','','','','system','9900','2006/10/01 01:01:01','SYS_Designer','2015/12/16 16:20:41','','');



-- sdong 	20151125 	在企业信用评估练习中增加相应字段
--	select * from evaluate_model  where modelno = 'ds100'

INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','01','1','经营管理者和员工素质','','!公用方法.取得模型单项值(#SerialNo,02)+!公用方法.取得模型单项值(#SerialNo,03)+!公用方法.取得模型单项值(#SerialNo,08)+!公用方法.取得模型单项值(#SerialNo,12)+!公用方法.取得模型单项值(#SerialNo,15)','','Number','#ItemValue',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','02','1.1','董事长学历','','','学历','Number','if(#ItemValue=1,2,if(#ItemValue=2,1.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','03','1.2','总经理','','!公用方法.取得模型单项值(#SerialNo,04)+!公用方法.取得模型单项值(#SerialNo,05)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','04','1.2.1','学历','','','总经理学历','Number','if(#ItemValue=1,4,if(#ItemValue=2,2,if(#ItemValue=3,0,if(#ItemValue=4,5,if(#ItemValue=5,8,0)))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','05','1.2.2','总经理本职年限','','!公用方法.取得模型单项值(#SerialNo,06)+!公用方法.取得模型单项值(#SerialNo,07)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','06','1.2.2.1','行业年限','','','行业年限','Number','if(#ItemValue=1,2,if(#ItemValue=2,1,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','07','1.2.2.2','职务年限','','','职务年限','Number','if(#ItemValue=1,2,if(#ItemValue=2,1,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','08','1.3','企业决策经营班子学历综合测评','','!信用等级评估.投资管理学历得分(#SerialNo)','','Number','if(#ItemValue>5,5,#ItemValue)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','1.1.3.1','1.3.1','研究生及研究生以上','','','','Number','#ItemValue*1.2',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','1.1.3.2','1.3.2','本科生','','','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','1.1.3.3','1.3.3','大专','','','','Number','#ItemValue*0.8',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','12','1.4','员工整体素质','','!公用方法.取得模型单项值(#SerialNo,13)+!公用方法.取得模型单项值(#SerialNo,14)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','13','1.4.1','全体员工本科以上学历占比','','','','Number','if(#ItemValue>0.5,4,if(#ItemValue>0.2,#ItemValue*0.8,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','14','1.4.2','员工学科多样性','','','员工学科多样性','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','15','1.5','法人代表有无逃废债记录','','','d有无','Number','if(#ItemValue=1,-10,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','16','2','企业经营管理素质','','!公用方法.取得模型单项值(#SerialNo,17)+!公用方法.取得模型单项值(#SerialNo,18)+!公用方法.取得模型单项值(#SerialNo,19)+!公用方法.取得模型单项值(#SerialNo,23)+!公用方法.取得模型单项值(#SerialNo,26)+!公用方法.取得模型单项值(#SerialNo,27)+!公用方法.取得模型单项值(#SerialNo,28)+!公用方法.取得模型单项值(#SerialNo,29)+!公用方法.取得模型单项值(#SerialNo,33)+!公用方法.取得模型单项值(#SerialNo,34)+!公用方法.取得模型单项值(#SerialNo,39)+!公用方法.取得模型单项值(#SerialNo,40)','','Number','#ItemValue',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','17','2.1.1','企业产权制度','','','d企业产权制度','Number','if(#ItemValue=1,3.5,if(#ItemValue=2,2.5,if(#ItemValue=3,2,if(#ItemValue=4,1.5,if(#ItemValue=5,1,0)))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','18','2.1.2','是否为财政投融资窗口','','','财政投融资窗口','Number','if(#ItemValue=1,6,if(#ItemValue=2,4,if(#ItemValue=3,2,0)))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','19','2.2','企业组织机构设置','','!公用方法.取得模型单项值(#SerialNo,20)+!公用方法.取得模型单项值(#SerialNo,21)+!公用方法.取得模型单项值(#SerialNo,22)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','20','2.2.1','董事会','','','董事会设置','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.2,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','21','2.2.2','监事会','','','监事会设置','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.2,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','22','2.2.3','家族企业','','','是否','Number','if(#ItemValue=1,-1.5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','23','2.3','管理制度','','!公用方法.取得模型单项值(#SerialNo,24)+!公用方法.取得模型单项值(#SerialNo,25)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','24','2.3.1','财务制度','','','d有无','Number','if(#ItemValue=1,0.5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','25','2.3.2','内部管理制度','','','d有无','Number','if(#ItemValue=1,0.5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','26','2.4','企业经营年限','','','SMECreditYear','Number','if(#ItemValue=3,-2,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','27','2.5','控股投资人背景','','','投资控股投资人背景','Number','if(#ItemValue=1,3,if(#ItemValue=2,2,if(#ItemValue=3,2,if(#ItemValue=4,1.5,if(#ItemValue=5,1,if(#ItemValue=6,1,if(#ItemValue=7,0,if(#ItemValue=8,-2,0))))))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','28','2.6','控股投资人与其关系','','','控股投资人与其关系','Number','if(#ItemValue=1,2,if(#ItemValue=2,1.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','29','2.7','融资渠道','','!公用方法.取得模型单项值(#SerialNo,30)+!公用方法.取得模型单项值(#SerialNo,31)+!公用方法.取得模型单项值(#SerialNo,32)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','30','2.7.1.1','上市','','','上市情况','Number','if(#ItemValue=1,5,if(#ItemValue=2,2,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','31','2.7.1.2','发债','','','发债情况','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,2,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','32','2.7.2','银行融资','','','银行融资情况','Number','if(#ItemValue=2,0.5,if(#ItemValue=1,3,if(#ItemValue=3,2,if(#ItemValue=4,1,0))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','33','2.8','投资评价','','','投资评价','Number','if(#ItemValue=1,1.5,if(#ItemValue=2,1,if(#ItemValue=3,0.5,0)))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','34','2.9','企业信用度','','!公用方法.取得模型单项值(#SerialNo,35)+!公用方法.取得模型单项值(#SerialNo,36)+!公用方法.取得模型单项值(#SerialNo,37)+!公用方法.取得模型单项值(#SerialNo,38)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','35','2.9.1','有无欠息','','','欠息情况','Number','if(#ItemValue=1,3,if(#ItemValue=2,1.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','36','2.9.2','有无逾期','','','逾期情况','Number','if(#ItemValue=1,3,if(#ItemValue=2,1.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','37','2.9.3','有无退票','','','d有无','Number','if(#ItemValue=1,-1,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','38','2.9.4','贷款中有无借新还旧或展期','','','d有无','Number','if(#ItemValue=1,-1,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','39','2.90','决策机制','','','决策机制','Number','if(#ItemValue=1,2,if(#ItemValue=2,0,-2))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','40','2.91','成长性','','','成长性','Number','if(#ItemValue=1,1,if(#ItemValue=2,0,-1))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','41','3','主导产品及技术创新','','!公用方法.取得模型单项值(#SerialNo,42)+!公用方法.取得模型单项值(#SerialNo,43)+!公用方法.取得模型单项值(#SerialNo,44)+!公用方法.取得模型单项值(#SerialNo,47)+!公用方法.取得模型单项值(#SerialNo,48)+!公用方法.取得模型单项值(#SerialNo,49)+!公用方法.取得模型单项值(#SerialNo,50)+!公用方法.取得模型单项值(#SerialNo,51)+!公用方法.取得模型单项值(#SerialNo,52)','','Number','#ItemValue',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','42','3.1','质量','','','产品质量','Number','if(#ItemValue=1,5,if(#ItemValue=2,0.3,if(#ItemValue=3,0,if(#ItemValue=4,-0.5,0))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','43','3.2','产销率','','','d产销率','Number','if(#ItemValue=1,1.5,if(#ItemValue=2,1,if(#ItemValue=3,0.5,0)))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','44','3.3','市场占有率','','!公用方法.取得模型单项值(#SerialNo,45)+!公用方法.取得模型单项值(#SerialNo,46)','','Number','#ItemValue',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','45','3.3.1','全国','','','全国市场占有率','Number','if(#ItemValue=1,2,if(#ItemValue=2,0.8,if(#ItemValue=3,0.8,if(#ItemValue=4,0.6,if(#ItemValue=5,0.4,0)))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','46','3.3.2','省、市','','','省市占有率','Number','if(#ItemValue=1,1.2,if(#ItemValue=2,0.8,if(#ItemValue=3,0.4,0)))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','47','3.4.1','通过ISO系列质量管理认证','','','d有无','Number','if(#ItemValue=1,1,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','48','3.4.2','获欧美日产品准入证','','','d有无','Number','if(#ItemValue=1,2,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','49','3.5','技术人员的比重','','','技术人员的比重','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,if(#ItemValue=3,0.3,if(#ItemValue=4,0.1,0))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','50','3.6','科研经费的比重','','','科研经费的比重','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.3,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','51','3.7','科研组织','','','科研组织','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,if(#ItemValue=3,0.3,0)))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','52','3.8','产品更新换代','','','产品更新换代','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.3,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','53','4','经营环境、市场环境','','!公用方法.取得模型单项值(#SerialNo,54)+!公用方法.取得模型单项值(#SerialNo,57)+!公用方法.取得模型单项值(#SerialNo,58)+!公用方法.取得模型单项值(#SerialNo,59)+!公用方法.取得模型单项值(#SerialNo,64)+!公用方法.取得模型单项值(#SerialNo,65)','','Number','#ItemValue',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','55','4.1.1','国家','','','d国家产业政策','Number','if(#ItemValue=1,2,if(#ItemValue=2,1,if(#ItemValue=3,0,if(#ItemValue=4,-2,0))))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','56','4.1.2','地方','','','d地方产业政策','Number','if(#ItemValue=1,1,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','58','4.3','行业门槛（专有技术）','','','d行业门槛','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','61','4.4.2','人力资源','','','人力资源','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','62','4.4.3','法律保障','','','d法律保障','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','63','4.4.4','基础设施','','','基础设施','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','64','4.5','市场竞争状态','','','市场竞争状态','Number','if(#ItemValue=1,1,if(#ItemValue=2,0,-1))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','65','4.6','行业排名','','','地方排名','Number','if(#ItemValue=1,2,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','66','5','重大事项','','!公用方法.取得模型单项值(#SerialNo,67)+!公用方法.取得模型单项值(#SerialNo,68)+!公用方法.取得模型单项值(#SerialNo,69)+!公用方法.取得模型单项值(#SerialNo,70)','','Number','#ItemValue',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','67','5.1','有重大诉讼纠纷（合计净资产10%以上）','','','d有无','Number','if(#ItemValue=1,-5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','68','5.2','主要经营管理人员的经济犯罪','','','d有无','Number','if(#ItemValue=1,-3,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','69','5.3','重大违规经营（走私、偷漏税、骗取银行贷款等）','','','d有无','Number','if(#ItemValue=1,-5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','70','5.4','重大事故造成重大损失（超过净资产20%以上）','','','d有无','Number','if(#ItemValue=1,-5,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('ds100','71','5.5','重大投资失败（超过净资产20%以上）','','','d有无','Number','if(#ItemValue=1,-5,0)',0.000000,'');

