/*****evaluate_catalog中新增一个"信用等级评估(练习)"评级模型*******/
--select * from evaluate_catalog where modelno='300';
INSERT INTO evaluate_catalog (MODELNO,MODELNAME,MODELTYPE,MODELDESCRIBE,TRANSFORMMETHOD,REMARK) VALUES ('300','信用等级评估(练习)','100','','if(#TotalScore<40,"D",if(#TotalScore<45,"C",if(#TotalScore<50,"CC",if(#TotalScore<60,"CCC",if(#TotalScore<65,"B",if(#TotalScore<70,"BB",if(#TotalScore<80,"BBB",if(#TotalScore<88,"A",if(#TotalScore<96,"AA","AAA"))))))))) ','');



/***code_library中加入"信用等级评估(练习)"*****/
--select * from code_library where codeno='CreditTempletType' and itemno='300';
INSERT INTO code_library (CODENO,ITEMNO,ITEMNAME,BANKNO,SORTNO,ISINUSE,ITEMDESCRIBE,ITEMATTRIBUTE,RELATIVECODE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK,HELPTEXT) VALUES ('CreditTempletType','300','信用等级评估(练习)','','300','1','300','','','','','','','','','','','system','9900',sysdate,'SYS_Designer',sysdate,'','');


/****新增"信用等级评估(练习)"评级模型的相关项*****/
--SELECT * FROM evaluate_model where modelno='300';
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1','1','经营管理者和员工素质','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1','1.1','学历情况',null,null,null,null,null,0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.1','1.1.1','研究生数','','','','Number','#ItemValue*1.2',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.2','1.1.2','本科生数','','','','Number','#ItemValue*1',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.3','1.1.3','大专生数','','','','Number','#ItemValue*0.8',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.4','1.1.4','中专生数',null,null,null,'Number','#ItemValue*0.5  ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.5','1.1.5','总经理学历是博士','','','是否','Number','if(#ItemValue=1,1,0)  ',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.1.6','1.1.6','学历得分',null,'!信用等级评估.学历加权得分1(#SerialNo)',null,'Number','if(#ItemValue>2,2,#ItemValue) ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.2','1.2','总经理本职年限','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.2.1','1.2.1','行业年限','','','行业年限','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.2.2','1.2.2','职务年限','','','职务年限','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,0))',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.3','1.3','法人代表有无逃废债记录','','','有无','Number','if(#ItemValue=1,-10,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','1.4','1.4','总经理是全国劳模','','','是否','Number','if(#ItemValue=1.0,1,0.0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2','2','企业经营管理素质','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.1','2.1','企业产权制度','','','企业产权制度','Number','if(#ItemValue=1,3.5,if(#ItemValue=2,2.5,if(#ItemValue=3,2,if(#ItemValue=4,1.5,if(#ItemValue=5,1,0)))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.2','2.2','企业组织机构设置','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.2.1','2.2.1','董事会','','','董事会设置','Number','if(!信用等级评估.是否家族企业(#SerialNo)=1,0,if(#ItemValue=1,0.4,if(#ItemValue=2,0.2,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.2.2','2.2.2','监事会','','','监事会设置','Number','if(!信用等级评估.是否家族企业(#SerialNo)=1,0,if(#ItemValue=1,0.2,if(#ItemValue=2,0.1,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.2.3','2.2.3','人、财、物、产、供、销6个部门','','','人财物产供销部门设置','Number','if(!信用等级评估.是否家族企业(#SerialNo)=1,0,if(#ItemValue=1,0.9,if(#ItemValue=2,0.6,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.2.4','2.2.4','家族企业','','','是否','Number','if(#ItemValue=1.0,1.0,-1.5)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.3','2.3','管理制度','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.3.1','2.3.1','财务制度','','','有无','','if(#ItemValue=1.0,0.25,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.3.2','2.3.2','供产销制度','','','有无','','if(#ItemValue=1.0,0.25,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.4','2.4','企业经营年限在一年以内','','','是否','','if(#ItemValue=1.0,-2,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.5','2.5','控股投资人背景',null,null,'控股投资人背景','Number','if(#ItemValue=1,3,if(#ItemValue=2,2,if(#ItemValue=3,2,if(#ItemValue=4,1,if(#ItemValue=5,1,if(#ItemValue=6,0,-2))))))  ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.6','2.6','控股投资人与其关系',null,null,'控股投资人与其关系','Number','if(#ItemValue=1,2,if(#ItemValue=2,1.5,0)) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.6.1','2.6.1','是否抽逃、侵占被投资人资金',null,null,'是否','Number','if(#ItemValue=1,-2,0) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.7','2.7','经营管理目标',null,null,'有无','Number','if(#ItemValue=1,0.5,0)  ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.8','2.8','营销策略及措施',null,null,'有无','Number','if(#ItemValue=1,0.5,0)  ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9','2.9','融资渠道',null,null,null,null,null,null,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9.1','2.9.1','上市',null,null,'上市情况','Number','if(#ItemValue=1,4,if(#ItemValue=2,1,0)) ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9.2','2.9.2','发债',null,null,'发债情况','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,2,0)) ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9.3','2.9.3','银行融资',null,null,'银行融资情况','Number','if(#ItemValue=1,3,if(#ItemValue=2,2.5,if(#ItemValue=3,2,if(#ItemValue=4,1,0)))) ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9.3.1','2.9.3.1','是否取得公开授信额度',null,null,'是否','Number','if(#ItemValue=1,1,0)  ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.9.4','2.9.4','商业融资',null,null,'商业融资情况','Number','if(#ItemValue=1,0.5,0)  ',0.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.a','2.a','投资策略',null,null,'投资策略','Number','if(#ItemValue=1,1.5,if(#ItemValue=2,1,if(#ItemValue=3,0.5,if(#ItemValue=4,0,1)))) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.b','2.b','企业信用度',null,null,null,null,null,null,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.b.1','2.b.1','有无欠息',null,null,'欠息情况','Number','if(#ItemValue=1,3,if(#ItemValue=2,1.5,if(#ItemValue=3,0,if(#ItemValue=4,-3,-6)))) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.b.2','2.b.2','有无逾期',null,null,'逾期情况','Number','if(#ItemValue=1,3,if(#ItemValue=2,1.5,if(#ItemValue=3,0,if(#ItemValue=4,-3,-6)))) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.b.3','2.b.3','有无退票',null,null,'有无','Number','if(#ItemValue=1,-1,0) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.b.4','2.b.4','贷款中有无借新还旧或展期',null,null,'有无','Number','if(#ItemValue=1,-1,0) ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','2.c','2.c','成长性',null,null,'成长性','Number','if(#ItemValue=1,1,if(#ItemValue=2,0,-1))  ',1.000000,null);
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3','3','主导产品及技术创新','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.1','3.1','质量','','','产品质量','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.3,if(#ItemValue=3,0,-0.5)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.2','3.2','产销率','','','产销情况','Number','if(#ItemValue=1.0,1.5,if(#ItemValue=2.0,1.0,if(#ItemValue=3.0,0.5,0.0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.3','3.3','市场占有率','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.3.1','3.3.1','全国','','','全国市场占有率','Number','if(#ItemValue=1,2,if(#ItemValue=2,0.8,if(#ItemValue=3,0.6,if(#ItemValue=4,0.4,0))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.3.2','3.3.2','省、市','','','省市占有率','Number','if(#ItemValue=1,1.2,if(#ItemValue=2,0.8,if(#ItemValue=3,0.4,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.4.1','3.4.1','通过ISO系列质量管理认证','','','是否','Number','if(#ItemValue=1,1,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.4.2','3.4.2','获欧美日产品准入证','','','是否','Number','if(#ItemValue=1,2,0)',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.5','3.5','技术人员的比重','','','技术人员的比重','Number','if(#ItemValue=1.0,1.0,if(#ItemValue=2,0.5,if(#ItemValue=3,0.3,if(#ItemValue=4,0.1,0.0))))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.6','3.6','科研经费的比重','','','科研经费的比重','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.3,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.7','3.7','科研组织','','','科研组织','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,if(#ItemValue=3,0.3,0)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','3.8','3.8','产品更新换代','','','产品更新换代','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.3,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4','4','经营环境、市场环境','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.1','4.1','产业政策','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.1.1','4.1.1','国家','','','国家产业政策','Number','if(#ItemValue=1,2,if(#ItemValue=2,1,if(#ItemValue=3,0,-2)))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.1.2','4.1.2','地方','','','地方产业政策','Number','if(#ItemValue=1,1,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.2','4.2','税收政策','','','税收政策','Number','if(#ItemValue=1,1,if(#ItemValue=2,0,-1))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.3','4.3','行业门槛（专有技术）','','','行业门槛','Number','if(#ItemValue=1,1,if(#ItemValue=2,0.5,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.4','4.4','投资环境','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.4.1','4.4.1','信息','','','信息环境','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.4.2','4.4.2','人力资源','','','人力资源','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.4.3','4.4.3','法律保障','','','法律保障','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.4.4','4.4.4','基础设施','','','基础设施','Number','if(#ItemValue=1,0.5,if(#ItemValue=2,0.25,0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.5','4.5','市场竞争状态','','','市场竞争状态','Number','if(#ItemValue=1.0,1,if(#ItemValue=2.0,0.0,-1.0))',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','4.6','4.6','行业排名全国是否前五','','','是否','Number','if(#ItemValue=1,2,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5','5','重大事项','','','','','',0.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5.1','5.1','有重大诉讼纠纷（合计净资产10%以上）','','','有无','Number','if(#ItemValue=1,-5,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5.2','5.2','主要经营管理人员的经济犯罪','','','有无','Number','if(#ItemValue=1,-3,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5.3','5.3','重大违规经营（走私、偷漏税、骗取银行贷款等）','','','有无','Number','if(#ItemValue=1,-5,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5.4','5.4','重大事故造成重大损失（超过净资产20%以上）','','','有无','Number','if(#ItemValue=1,-5,0)',1.000000,'');
INSERT INTO evaluate_model (MODELNO,ITEMNO,DISPLAYNO,ITEMNAME,ITEMATTRIBUTE,VALUEMETHOD,VALUECODE,VALUETYPE,EVALUATEMETHOD,COEFFICIENT,REMARK) VALUES ('300','5.5','5.5','重大投资失败（超过净资产20%以上）','','','有无','Number','if(#ItemValue=1,-5,0)',1.000000,'');



/*************方法设置中添加一条方法记录*******************/
--select * from class_method where methodname='学历加权得分1';
INSERT INTO class_method (CLASSNAME,METHODNAME,METHODTYPE,METHODDESCRIBE,RETURNTYPE,METHODARGS,METHODCODE,INPUTUSER,INPUTORG,INPUTTIME,UPDATEUSER,UPDATETIME,REMARK) VALUES ('信用等级评估','学历加权得分1','Bizlet','','String','String SerialNo','com.amarsoft.app.lending.bizlets.getEducationScore2','','','','','','');











